"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";

const healthOptions=["Well","Mild","Moderate","Severe"], stoolOptions=["Not logged","Formed","Loose","Watery","Constipated"], mealTypes=["breakfast","lunch","dinner"] as const;
type MealType=typeof mealTypes[number];
type Food={id:string;name:string;category:string;default_portion:string|null};
type Meal={id:string;meal_type:MealType;food_name:string;eaten_at:string;portion:string|null;symptoms_after:string|null};
type Preference={food_id:string;preference:string;tolerance:string};
type Template={id:string;name:string;meal_type:MealType;description:string;food_ids:string[];substitution_note:string|null};

export default function Home(){
 const [loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[message,setMessage]=useState("");
 const [foods,setFoods]=useState<Food[]>([]),[templates,setTemplates]=useState<Template[]>([]),[preferences,setPreferences]=useState<Record<string,Preference>>({}),[recentMeals,setRecentMeals]=useState<Meal[]>([]),[meals,setMeals]=useState<Meal[]>([]);
 const [healthStatus,setHealthStatus]=useState("Well"),[stoolType,setStoolType]=useState("Not logged"),[energy,setEnergy]=useState(3),[water,setWater]=useState(0),[pain,setPain]=useState(0),[urgency,setUrgency]=useState(0),[notes,setNotes]=useState("");
 const [mealType,setMealType]=useState<MealType>("breakfast"),[selectedFoodIds,setSelectedFoodIds]=useState<string[]>([]),[customFood,setCustomFood]=useState(""),[portion,setPortion]=useState(""),[symptomsAfter,setSymptomsAfter]=useState(""),[mealNotes,setMealNotes]=useState(""),[foodSearch,setFoodSearch]=useState("");
 const today=new Date().toISOString().slice(0,10);

 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();setSignedIn(!!user);
  const {data:fs}=await s.from("food_catalog").select("id,name,category,default_portion").order("name");setFoods((fs as Food[])||[]);
  const {data:ts}=await s.from("meal_templates").select("*").eq("is_active",true).order("meal_type,name");setTemplates((ts as Template[])||[]);
  if(user){await loadToday(user.id);await loadHistory(user.id);const {data:p}=await s.from("user_food_preferences").select("food_id,preference,tolerance").eq("user_id",user.id);setPreferences(Object.fromEntries(((p as Preference[])||[]).map(x=>[x.food_id,x])));}
  setLoading(false);})();},[]);

 async function loadToday(userId:string){const s=createClient(),start=new Date(today+"T00:00:00").toISOString(),end=new Date(today+"T23:59:59.999").toISOString();const {data}=await s.from("meal_logs").select("*").eq("user_id",userId).gte("eaten_at",start).lte("eaten_at",end).order("eaten_at",{ascending:false});setMeals((data as Meal[])||[]);}
 async function loadHistory(userId:string){const since=new Date(Date.now()-7*86400000).toISOString();const {data}=await createClient().from("meal_logs").select("*").eq("user_id",userId).gte("eaten_at",since).order("eaten_at",{ascending:false});setRecentMeals((data as Meal[])||[]);}
 const recentFoods=useMemo(()=>new Set(recentMeals.flatMap(m=>m.food_name.toLowerCase().split(",").map(x=>x.trim()))),[recentMeals]);
 const allowed=useMemo(()=>new Set(foods.filter(f=>!["avoid","unavailable"].includes(preferences[f.id]?.preference||"")).map(f=>f.id)),[foods,preferences]);
 const rankedTemplates=useMemo(()=>templates.filter(t=>t.meal_type===mealType).map(t=>{const recent=t.food_ids.filter(id=>recentFoods.has(foods.find(f=>f.id===id)?.name.toLowerCase()||""));const blocked=t.food_ids.filter(id=>!allowed.has(id));const liked=t.food_ids.filter(id=>preferences[id]?.preference==="like"||preferences[id]?.tolerance==="tolerated");return {...t,recentCount:recent.length,blockedCount:blocked.length,likedCount:liked.length};}).filter(t=>t.blockedCount===0).sort((a,b)=>(b.likedCount-a.likedCount)||(a.recentCount-b.recentCount))),[templates,mealType,recentFoods,allowed,preferences,foods]);
 const selectedTemplate=rankedTemplates[0];

 function useTemplate(t:Template){setMealType(t.meal_type);setSelectedFoodIds(t.food_ids.filter(id=>allowed.has(id)));setCustomFood("");setMealNotes(t.description);window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"});}
 async function saveCheckin(){const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){location.href="/auth";return;}const {error}=await s.from("daily_logs").upsert({user_id:user.id,log_date:today,health_status:healthStatus,stool_type:stoolType,pain_score:pain,urgency_score:urgency,energy_score:energy,water_glasses:water,notes:notes||null},{onConflict:"user_id,log_date"});setMessage(error?error.message:"Today's private check-in was saved.");}
 async function addMeal(){const names=[...foods.filter(f=>selectedFoodIds.includes(f.id)).map(f=>f.name),...customFood.split(",").map(x=>x.trim()).filter(Boolean)];if(!names.length){setMessage("Choose a food or add a custom food.");return;}const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){location.href="/auth";return;}const {error}=await s.from("meal_logs").insert({user_id:user.id,meal_type:mealType,food_name:names.join(", "),portion:portion||null,symptoms_after:symptomsAfter||null,notes:mealNotes||null});if(error){setMessage(error.message);return;}setSelectedFoodIds([]);setCustomFood("");setPortion("");setMealNotes("");setSymptomsAfter("");await loadToday(user.id);await loadHistory(user.id);setMessage("Meal saved privately.");}
 async function savePreference(foodId:string,preference:string,tolerance?:string){const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){location.href="/auth";return;}const prev=preferences[foodId],next={food_id:foodId,preference,tolerance:tolerance||prev?.tolerance||"unknown"};const {error}=await s.from("user_food_preferences").upsert({user_id:user.id,...next},{onConflict:"user_id,food_id"});if(error){setMessage(error.message);return;}setPreferences(x=>({...x,[foodId]:next}));}
 async function deleteMeal(id:string){const {error}=await createClient().from("meal_logs").delete().eq("id",id);if(error){setMessage(error.message);return;}setMeals(x=>x.filter(m=>m.id!==id));setRecentMeals(x=>x.filter(m=>m.id!==id));}
 async function signOut(){await createClient().auth.signOut();location.href="/auth";}
 if(loading)return <main><p>Loading your private dashboard…</p></main>;
 const visible=foods.filter(f=>f.name.toLowerCase().includes(foodSearch.toLowerCase())||f.category.toLowerCase().includes(foodSearch.toLowerCase())).filter(f=>allowed.has(f.id));
 const templateFoods=(selectedTemplate?.food_ids||[]).map(id=>foods.find(f=>f.id===id)?.name).filter(Boolean).join(" + ");
 return <main><header><h1>PendaFood</h1><p className="muted">Food, symptoms, stool and habits — kept simple and private.</p>{signedIn?<button onClick={signOut}>Sign out</button>:<a href="/auth">Sign in</a>}</header>
 <section className="card"><h2>Meal planner</h2><div className="grid"><label>Meal type<select value={mealType} onChange={e=>setMealType(e.target.value as MealType)}>{mealTypes.map(x=><option key={x}>{x}</option>)}</select></label><div><h3>{selectedTemplate?.name||"No matching template yet"}</h3>{selectedTemplate&&<><p>{selectedTemplate.description}</p><p><strong>Foods:</strong> {templateFoods}</p><p className="muted">Why: {selectedTemplate.recentCount===0?"None of its foods were logged in the last 7 days.":selectedTemplate.recentCount+" food(s) were recently logged."} {selectedTemplate.likedCount?"Some foods match your like/tolerated preferences.":""}</p><button onClick={()=>useTemplate(selectedTemplate)}>Use this meal</button></>}</div></div><h3>Other options</h3><div className="grid">{rankedTemplates.slice(1,4).map(t=><div key={t.id}><strong>{t.name}</strong><p className="muted">{t.description}</p><button onClick={()=>useTemplate(t)}>Use</button></div>)}</div></section>
 <section className="card"><h2>Today's gut check-in</h2><div className="grid"><label>Overall health<select value={healthStatus} onChange={e=>setHealthStatus(e.target.value)}>{healthOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Stool today<select value={stoolType} onChange={e=>setStoolType(e.target.value)}>{stoolOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Energy (1–5)<input type="number" min="1" max="5" value={energy} onChange={e=>setEnergy(+e.target.value)}/></label><label>Water glasses<input type="number" min="0" max="30" value={water} onChange={e=>setWater(+e.target.value)}/></label><label>Pain (0–10)<input type="number" min="0" max="10" value={pain} onChange={e=>setPain(+e.target.value)}/></label><label>Urgency (0–3)<input type="number" min="0" max="3" value={urgency} onChange={e=>setUrgency(+e.target.value)}/></label></div><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label><button onClick={saveCheckin}>Save today's check-in</button></section>
 <section className="card"><h2>Build a meal</h2><div className="grid"><label>Search foods<input value={foodSearch} onChange={e=>setFoodSearch(e.target.value)} placeholder="Search foods"/></label><label>Portion<input value={portion} onChange={e=>setPortion(e.target.value)}/></label></div><div className="food-list">{visible.map(f=><label key={f.id} className="food-option"><input type="checkbox" checked={selectedFoodIds.includes(f.id)} onChange={()=>setSelectedFoodIds(x=>x.includes(f.id)?x.filter(v=>v!==f.id):[...x,f.id])}/><strong>{f.name}</strong><span className="muted"> ({f.category})</span></label>)}</div><label>Custom foods<input value={customFood} onChange={e=>setCustomFood(e.target.value)} placeholder="Comma separated"/></label><div className="grid"><label>Symptoms after<input value={symptomsAfter} onChange={e=>setSymptomsAfter(e.target.value)}/></label></div><label>Meal notes<textarea value={mealNotes} onChange={e=>setMealNotes(e.target.value)} rows={2}/></label><button onClick={addMeal}>Save this meal</button></section>
 <section className="card"><h2>My food preferences</h2>{foods.map(f=>{const p=preferences[f.id];return <div className="food-option" key={f.id}><strong>{f.name}</strong><span className="muted">{p?" · "+p.preference+" · "+p.tolerance:""}</span><div><button onClick={()=>savePreference(f.id,"like")}>Like</button><button onClick={()=>savePreference(f.id,"unavailable")}>Unavailable</button><button onClick={()=>savePreference(f.id,"avoid")}>Avoid</button><button onClick={()=>savePreference(f.id,p?.preference||"neutral","tolerated")}>Tolerated</button><button onClick={()=>savePreference(f.id,p?.preference||"neutral","problematic")}>Problematic</button></div></div>})}</section>
 <section className="card"><h2>Today's meals</h2>{meals.length?<ul>{meals.map(m=><li key={m.id}><strong>{m.meal_type}</strong>: {m.food_name} <button onClick={()=>deleteMeal(m.id)}>Delete</button></li>)}</ul>:<p className="muted">Nothing logged yet.</p>}</section>{message&&<p role="status">{message}</p>}<section className="card"><h2>Privacy</h2><p className="muted">Your health records and preferences remain private to your account.</p></section></main>;
}
